"""All user-facing strings, Persian (primary) + English. Values use a small HTML subset (<b> <i> <code> <a>) – each platform transport renders it.
Keys must exist in both languages (checked by test_offline.py)."""

BRAND_FA, BRAND_EN = "فروشگاه", "Shop"

FA = {
 "pick_lang": "🌐 زبان را انتخاب کن / Choose your language:",
 "lang_set": "✅ زبان روی فارسی تنظیم شد.",
 "welcome": "🌸 سلام {name}!\nبه <b>فروشگاه</b> خوش اومدی ✨\nلوازم آرایشی و زیبایی، یه کلیک اونورتر 💄\n\nچطور می‌تونم کمکت کنم؟ 👇",
 "menu_title": "🏠 منوی اصلی — یکی از گزینه‌ها را انتخاب کن 👇",
 "hint_menu": "برای دیدن منو /start را بزن 🌸",
 "cancelled": "لغو شد ✅",
 "help": "🌸 <b>راهنما</b>\n/start — منوی اصلی\n/lang — تغییر زبان\n/cancel — انصراف از عملیات جاری",
 # buttons
 "b_products": "🛍 محصولات", "b_search": "🔍 جستجو", "b_track": "📦 پیگیری سفارش", "b_orders": "🧾 سفارش‌های من",
 "b_support": "💬 پشتیبانی", "b_faq": "❓ سوالات متداول", "b_about": "📞 درباره / تماس", "b_lang": "🌐 زبان",
 "b_admin": "🛠 پنل مدیریت", "b_menu": "🏠 منو", "b_back": "⬅️ بازگشت", "b_cats": "🗂 دسته‌ها",
 "b_prev": "◀️ قبلی", "b_next": "بعدی ▶️", "b_site": "🔗 مشاهده در سایت", "b_cancel": "❌ لغو",
 "b_share": "📲 اشتراک‌گذاری شماره", "b_unlink": "🔓 حذف شماره‌ی من", "b_again": "🔁 دوباره", "b_support_short": "💬 پشتیبانی",
 # shop
 "shop_setup": "🌷 اتصال ربات به فروشگاه در حال آماده‌سازی است.\nخیلی زود این بخش فعال می‌شود؛ ممنون از صبرت 💕",
 "shop_error": "😔 الان نمی‌تونم به فروشگاه وصل بشم. کمی بعد دوباره امتحان کن یا از بخش پشتیبانی کمک بگیر.",
 "mock_banner": "🧪 <i>نمایش داده‌های نمونه — واقعی نیست</i>\n\n",
 "cats_title": "🗂 <b>دسته‌بندی محصولات</b>\nیکی را انتخاب کن 👇",
 "cats_empty": "هنوز دسته‌ای برای نمایش وجود ندارد 🌱",
 "prods_title": "🛍 <b>{cat}</b>\nصفحه‌ی {page} از {pages}",
 "prods_empty": "محصولی پیدا نشد 🌱",
 "search_ask": "🔍 نام محصول را بنویس و بفرست:\n(برای انصراف /cancel)",
 "search_title": "🔍 نتیجه‌ی «{q}»\nصفحه‌ی {page} از {pages}",
 "search_empty": "چیزی برای «{q}» پیدا نشد 🙈\nعبارت دیگری را امتحان کن.",
 "search_bad": "لطفاً یک عبارت کوتاه بنویس (حداقل ۲ حرف).",
 "expired": "این دکمه منقضی شده؛ دوباره از منو شروع کن 🌸",
 "product_gone": "این محصول دیگر پیدا نشد 🙈",
 "in_stock": "✅ موجود", "out_stock": "⛔️ ناموجود", "price": "💰 قیمت", "price_unknown": "—",
 # tracking
 "track_ask": "📦 <b>پیگیری سفارش</b>\nشماره‌ی سفارشت را بفرست:\n(برای انصراف /cancel)",
 "track_bad": "شماره‌ی سفارش معتبر نیست؛ فقط حروف/عدد و حداکثر ۴۰ کاراکتر. دوباره بفرست.",
 "phone_ask": "🔐 برای اطمینان از اینکه سفارش مال توست، شماره‌ی موبایلی را که با آن سفارش داده‌ای بفرست (مثل 09123456789) یا با دکمه‌ی زیر شماره‌ات را به اشتراک بگذار 👇",
 "phone_bad": "شماره‌ی موبایل معتبر نیست. دوباره بفرست (مثل 09123456789).",
 "order_notfound": "😕 سفارشی با این مشخصات پیدا نشد.\nشماره‌ی سفارش و شماره‌ی موبایل را بررسی کن.",
 "order_noverify": "🔒 به‌خاطر حفظ حریم خصوصی فعلاً امکان تأیید این سفارش از طریق ربات نیست. لطفاً از پشتیبانی بپرس 💬",
 "too_many": "⏳ تلاش‌های ناموفق زیاد بود. چند دقیقه‌ی دیگر دوباره امتحان کن.",
 "order_card": "📦 <b>سفارش {num}</b>\n{status}\n",
 "o_date": "📅 تاریخ", "o_total": "💰 مبلغ", "o_track": "🚚 کد رهگیری", "o_items": "🧴 اقلام",
 "orders_link": "🧾 <b>سفارش‌های من</b>\nبرای دیدن سفارش‌ها، شماره‌ی موبایلت را با دکمه‌ی زیر به اشتراک بگذار 👇\n(فقط شماره‌ی خودت پذیرفته می‌شود)",
 "orders_title": "🧾 <b>سفارش‌های من</b>\nشماره‌ی متصل: {phone}",
 "orders_empty": "هنوز سفارشی برای این شماره پیدا نشد 🌱",
 "linked": "✅ شماره‌ات ثبت شد.", "unlinked": "🔓 شماره‌ات حذف شد.",
 "contact_foreign": "⚠️ فقط شماره‌ی خودت را می‌توانی به اشتراک بگذاری.",
 # statuses
 "st_pending": "⏳ در انتظار پرداخت/بررسی", "st_paid": "💳 پرداخت شده", "st_processing": "🧴 در حال پردازش",
 "st_packed": "🎁 بسته‌بندی شد", "st_shipped": "🚚 ارسال شد", "st_delivered": "✅ تحویل داده شد 🎉",
 "st_canceled": "❌ لغو شده", "st_refunded": "💸 بازگشت وجه", "st_returned": "↩️ مرجوع شد",
 "st_failed": "⚠️ ناموفق", "st_on_hold": "⏸ معلق", "st_unknown": "❔ {raw}",
 "notify_update": "🔔 <b>به‌روزرسانی سفارش {num}</b>\n{status}",
 # support
 "support_ask": "💬 <b>پشتیبانی</b>\nپیامت را بنویس (متن، عکس، ...) تا برای تیم فروشگاه ارسال شود. پاسخ همین‌جا برایت می‌آید 💕\nبرای خروج «{menu}» را بزن.",
 "support_sent": "✅ پیامت ارسال شد؛ به‌زودی پاسخ می‌دهیم 💕",
 "support_saved": "✅ پیامت ثبت شد؛ به‌محض آماده شدن پشتیبان پاسخ می‌دهیم 💕",
 "support_reply": "💬 <b>پاسخ پشتیبانی فروشگاه:</b>",
 "support_closed": "✅ گفتگوی پشتیبانی شما بسته شد. برای پیام جدید دوباره «پشتیبانی» را بزن.",
 # faq/about
 "faq_title": "❓ <b>سوالات متداول</b>\n\n", "faq_empty": "هنوز سوالی ثبت نشده 🌱\nسوالت را از بخش پشتیبانی بپرس 💬",
 "about_title": "📞 <b>درباره‌ی فروشگاه / تماس</b>\n\n",
 "about_empty": "🌸 <b>فروشگاه لوازم آرایشی</b>.\nبرای ارتباط با ما از بخش «پشتیبانی» استفاده کن 💬",
 # admin
 "a_bound": "🔐 شما به‌عنوان مدیر ربات ثبت شدید (شناسه: <code>{uid}</code>). برای ورود /admin را بزن.",
 "a_denied": "این بخش فقط برای مدیر است 🔒",
 "a_home": "🛠 <b>پنل مدیریت فروشگاه</b>",
 "a_b_stats": "📊 آمار", "a_b_bc": "📢 پیام همگانی", "a_b_faq": "❓ ویرایش سوالات", "a_b_about": "📞 ویرایش درباره",
 "a_b_inbox": "📥 صندوق پشتیبانی ({n})", "a_b_api": "🔌 اتصال API / API connection",
 "a_stats": "📊 <b>آمار</b>\n👥 کاربران: {users}\n🟢 فعال ۷ روز اخیر: {active}\n📱 شماره‌ی متصل: {phones}\n🚫 مسدودکننده‌ی ربات: {blocked}\n💬 تیکت باز: {open_t} از {all_t}\n📢 پیام‌های همگانی: {bc}\n🔌 اتصال فروشگاه: {api}",
 "a_api_real": "واقعی ✅", "a_api_mock": "نمونه 🧪", "a_api_none": "تنظیم نشده ⚪️",
 "a_bc_ask": "📢 پیام همگانی را بفرست (متن یا عکس/رسانه). قبل از ارسال پیش‌نمایش و تأیید می‌گیری.\n/cancel برای انصراف",
 "a_bc_confirm": "👆 این پیام برای <b>{n}</b> کاربر ارسال می‌شود. تأیید می‌کنی؟",
 "a_bc_yes": "✅ ارسال شود", "a_bc_no": "❌ لغو",
 "a_bc_started": "🚀 ارسال شروع شد...", "a_bc_done": "📢 ارسال تمام شد.\n✅ موفق: {ok}\n🚫 ناموفق: {fail}",
 "a_bc_none": "کاربری برای ارسال وجود ندارد.", "a_bc_gone": "پیش‌نویسی وجود ندارد.",
 "a_text_menu": "{title}\n\n<b>فارسی:</b>\n{fa}\n\n<b>English:</b>\n{en}",
 "a_text_unset": "<i>(تنظیم نشده)</i>",
 "a_edit_fa": "✏️ ویرایش فارسی", "a_edit_en": "✏️ Edit English", "a_reset_fa": "↩️ حذف فارسی", "a_reset_en": "↩️ Reset English",
 "a_text_ask": "✏️ متن جدید را بفرست ({which}).\n/cancel برای انصراف",
 "a_saved": "✅ ذخیره شد.", "a_title_faq": "❓ <b>سوالات متداول</b>", "a_title_about": "📞 <b>درباره / تماس</b>",
 "a_inbox": "📥 <b>صندوق پشتیبانی</b>\nتیکت‌های باز: {n}", "a_inbox_empty": "تیکتی وجود ندارد 🌱",
 "a_ticket": "🎫 <b>تیکت #{id}</b> — {status}\n👤 {who}\n\n{msgs}",
 "a_t_open": "🟢 باز", "a_t_closed": "⚪️ بسته",
 "a_t_reply": "✍️ پاسخ", "a_t_close": "✅ بستن", "a_t_reopen": "🔄 بازگشایی", "a_t_inbox": "📥 صندوق",
 "a_t_ask": "✍️ پاسخ به تیکت #{id} را بفرست (متن یا رسانه).\n/cancel برای انصراف",
 "a_t_new": "📩 <b>تیکت #{id}</b> — {who}",
 "a_t_sent": "✅ پاسخ برای کاربر ارسال شد.", "a_t_fail": "⚠️ ارسال به کاربر ناموفق بود (احتمالاً ربات را مسدود کرده).",
 "a_t_none": "تیکت پیدا نشد.", "a_t_reply_hint": "برای پاسخ، دکمه‌ی «پاسخ» را بزن یا روی همان پیام Reply کن.",
 # api admin
 "api_home": "🔌 <b>اتصال API فروشگاه</b>\n\nوضعیت: {state}\n🌐 آدرس پایه: <code>{url}</code>\n🔑 کلید: <code>{key}</code>\n🔐 نوع احراز هویت: {auth}\n\n<i>منبع تنظیمات: {src}. مقادیر ثبت‌شده در پنل بر متغیرهای محیطی اولویت دارند.</i>",
 "api_on": "🟢 فعال", "api_off": "⚪️ غیرفعال", "api_incomplete": "🟡 ناقص (آدرس یا کلید ثبت نشده)",
 "api_unset": "ثبت نشده",
 "api_src_panel": "پنل", "api_src_env": "متغیر محیطی", "api_src_mixed": "پنل + متغیر محیطی",
 "api_b_url": "🌐 آدرس پایه", "api_b_key": "🔑 کلید API", "api_b_auth": "🔐 نوع احراز هویت", "api_b_paths": "🛣 مسیر endpointها",
 "api_b_fields": "🧬 نگاشت فیلدها", "api_b_test": "🧪 تست اتصال", "api_b_toggle_on": "⏻ غیرفعال کن", "api_b_toggle_off": "⏻ فعال کن",
 "api_b_clear": "🗑 حذف کلید",
 "api_url_ask": "🌐 آدرس پایه‌ی API را بفرست، مثلاً <code>https://example.com/api/v1</code>\n/cancel برای انصراف",
 "api_url_bad": "آدرس معتبر نیست؛ باید با http:// یا https:// شروع شود.",
 "api_url_http": "\n⚠️ این آدرس https نیست؛ کلید بدون رمزنگاری ارسال می‌شود.",
 "api_key_ask": "🔑 کلید/توکن API را بفرست. پیام تو بلافاصله بعد از ذخیره پاک می‌شود.\n/cancel برای انصراف",
 "api_key_saved": "✅ کلید ذخیره شد: <code>{key}</code>", "api_key_del_fail": "\n⚠️ نتوانستم پیام حاوی کلید را پاک کنم؛ خودت آن را پاک کن.",
 "api_key_cleared": "🗑 کلید حذف شد.",
 "api_key_bad": "کلید نامعتبر است (خالی/خیلی طولانی/دارای فاصله).",
 "api_auth_menu": "🔐 <b>نوع احراز هویت</b>\nفعلی: {cur}\nنام هدر/پارامتر: <code>{name}</code>",
 "api_as_bearer": "Bearer (Authorization)", "api_as_header": "هدر X-API-Key", "api_as_query": "پارامتر Query",
 "api_b_authname": "✏️ نام هدر/پارامتر", "api_authname_ask": "نام هدر یا پارامتر را بفرست (مثلاً <code>X-API-Key</code> یا <code>api_key</code>). برای بازگشت به پیش‌فرض یک <code>-</code> بفرست.",
 "api_authname_bad": "نام معتبر نیست (فقط حروف انگلیسی، عدد، - و _).",
 "api_paths_menu": "🛣 <b>مسیر endpointها</b> (نسبت به آدرس پایه)\nجاینشین‌ها: <code>{{id}} {{q}} {{page}} {{per_page}} {{category}} {{order}} {{phone}} {{user}} {{status}}</code>\n\n{lines}",
 "api_path_ask": "مسیر جدید برای <b>{name}</b> را بفرست.\nفعلی: <code>{cur}</code>\nپیش‌فرض: <code>{dflt}</code>\n(نباید آدرس کامل باشد، مثل <code>/products/{{id}}</code>)",
 "api_path_bad": "مسیر معتبر نیست؛ باید نسبی باشد (بدون http://) و کوتاه.",
 "api_reset": "↩️ پیش‌فرض", "api_custom": "(سفارشی)", "api_default": "(پیش‌فرض)",
 "api_fields_menu": "🧬 <b>نگاشت فیلدهای پاسخ JSON</b>\nگروه را انتخاب کن. هر مقدار می‌تواند چند کلید با کاما باشد (اولین موجود استفاده می‌شود؛ مسیر تو در تو با نقطه: <code>billing.phone</code>).",
 "api_fg_general": "⚙️ عمومی", "api_fg_category": "🗂 دسته", "api_fg_product": "🧴 محصول", "api_fg_order": "📦 سفارش",
 "api_fgroup": "🧬 <b>فیلدها — {g}</b>\n\n{lines}",
 "api_field_ask": "کلید(های) JSON برای <b>{name}</b> را بفرست.\nفعلی: <code>{cur}</code>\nپیش‌فرض: <code>{dflt}</code>",
 "api_field_bad": "مقدار معتبر نیست (حروف/عدد/نقطه/کاما/خط‌تیره، حداکثر ۱۰۰ کاراکتر).",
 "api_test_missing": "⚠️ ابتدا آدرس پایه و کلید را ثبت کن و اتصال را فعال کن.",
 "api_test_running": "🧪 در حال تست...",
 "api_test_ok": "🧪 <b>نتیجه‌ی تست</b>\n✅ وضعیت HTTP: {status}\n⏱ {ms} میلی‌ثانیه\n📄 تعداد آیتم در پاسخ: {count}\n{extra}",
 "api_test_ok_sample": "🧴 نمونه محصول: {s}",
 "api_test_ok_nomap": "⚠️ آیتمی شناخته نشد؛ کلیدهای دیده‌شده: <code>{keys}</code>\nنگاشت فیلدها را تنظیم کن.",
 "api_test_fail": "🧪 <b>نتیجه‌ی تست</b>\n❌ {err}\n⏱ {ms} میلی‌ثانیه",
}

EN = {
 "pick_lang": "🌐 زبان را انتخاب کن / Choose your language:",
 "lang_set": "✅ Language set to English.",
 "welcome": "🌸 Hi {name}!\nWelcome to the <b>Shop</b> ✨\nCosmetics & beauty, one tap away 💄\n\nHow can I help you? 👇",
 "menu_title": "🏠 Main menu — pick an option 👇",
 "hint_menu": "Send /start to see the menu 🌸",
 "cancelled": "Cancelled ✅",
 "help": "🌸 <b>Help</b>\n/start — main menu\n/lang — change language\n/cancel — cancel the current action",
 "b_products": "🛍 Products", "b_search": "🔍 Search", "b_track": "📦 Track order", "b_orders": "🧾 My orders",
 "b_support": "💬 Support", "b_faq": "❓ FAQ", "b_about": "📞 About / Contact", "b_lang": "🌐 Language",
 "b_admin": "🛠 Admin panel", "b_menu": "🏠 Menu", "b_back": "⬅️ Back", "b_cats": "🗂 Categories",
 "b_prev": "◀️ Prev", "b_next": "Next ▶️", "b_site": "🔗 View on website", "b_cancel": "❌ Cancel",
 "b_share": "📲 Share my number", "b_unlink": "🔓 Remove my number", "b_again": "🔁 Again", "b_support_short": "💬 Support",
 "shop_setup": "🌷 The connection to the shop is being set up.\nThis section will be available very soon — thanks for your patience 💕",
 "shop_error": "😔 I can't reach the shop right now. Please try again in a bit, or ask Support for help.",
 "mock_banner": "🧪 <i>Showing example data — not real</i>\n\n",
 "cats_title": "🗂 <b>Product categories</b>\nPick one 👇",
 "cats_empty": "No categories to show yet 🌱",
 "prods_title": "🛍 <b>{cat}</b>\nPage {page} of {pages}",
 "prods_empty": "No products found 🌱",
 "search_ask": "🔍 Type the product name and send it:\n(/cancel to abort)",
 "search_title": "🔍 Results for “{q}”\nPage {page} of {pages}",
 "search_empty": "Nothing found for “{q}” 🙈\nTry another phrase.",
 "search_bad": "Please type a short phrase (at least 2 characters).",
 "expired": "This button has expired; please start again from the menu 🌸",
 "product_gone": "This product could not be found anymore 🙈",
 "in_stock": "✅ In stock", "out_stock": "⛔️ Out of stock", "price": "💰 Price", "price_unknown": "—",
 "track_ask": "📦 <b>Track order</b>\nSend your order number:\n(/cancel to abort)",
 "track_bad": "Invalid order number; letters/digits only, max 40 characters. Send it again.",
 "phone_ask": "🔐 To make sure the order is yours, send the mobile number you ordered with (e.g. 09123456789) or share your number with the button below 👇",
 "phone_bad": "That mobile number isn't valid. Send it again (e.g. 09123456789).",
 "order_notfound": "😕 No order found with these details.\nPlease check the order number and mobile number.",
 "order_noverify": "🔒 For privacy reasons this order can't be verified through the bot right now. Please ask Support 💬",
 "too_many": "⏳ Too many failed attempts. Please try again in a few minutes.",
 "order_card": "📦 <b>Order {num}</b>\n{status}\n",
 "o_date": "📅 Date", "o_total": "💰 Total", "o_track": "🚚 Tracking code", "o_items": "🧴 Items",
 "orders_link": "🧾 <b>My orders</b>\nTo see your orders, share your mobile number with the button below 👇\n(only your own number is accepted)",
 "orders_title": "🧾 <b>My orders</b>\nLinked number: {phone}",
 "orders_empty": "No orders found for this number yet 🌱",
 "linked": "✅ Your number has been saved.", "unlinked": "🔓 Your number has been removed.",
 "contact_foreign": "⚠️ You can only share your own number.",
 "st_pending": "⏳ Pending payment/review", "st_paid": "💳 Paid", "st_processing": "🧴 Processing",
 "st_packed": "🎁 Packed", "st_shipped": "🚚 Shipped", "st_delivered": "✅ Delivered 🎉",
 "st_canceled": "❌ Canceled", "st_refunded": "💸 Refunded", "st_returned": "↩️ Returned",
 "st_failed": "⚠️ Failed", "st_on_hold": "⏸ On hold", "st_unknown": "❔ {raw}",
 "notify_update": "🔔 <b>Order {num} update</b>\n{status}",
 "support_ask": "💬 <b>Support</b>\nWrite your message (text, photo, ...) and it goes to the Shop team. The reply arrives right here 💕\nPress “{menu}” to leave.",
 "support_sent": "✅ Message sent; we'll reply soon 💕",
 "support_saved": "✅ Message saved; we'll reply as soon as support is available 💕",
 "support_reply": "💬 <b>Shop support replied:</b>",
 "support_closed": "✅ Your support conversation was closed. Press “Support” for a new message.",
 "faq_title": "❓ <b>FAQ</b>\n\n", "faq_empty": "No FAQ entries yet 🌱\nAsk your question via Support 💬",
 "about_title": "📞 <b>About Shop / Contact</b>\n\n",
 "about_empty": "🌸 <b>Cosmetics store</b>.\nUse “Support” to get in touch with us 💬",
 "a_bound": "🔐 You are registered as the bot admin (id: <code>{uid}</code>). Send /admin to open the panel.",
 "a_denied": "This section is for the admin only 🔒",
 "a_home": "🛠 <b>Shop admin panel</b>",
 "a_b_stats": "📊 Stats", "a_b_bc": "📢 Broadcast", "a_b_faq": "❓ Edit FAQ", "a_b_about": "📞 Edit About",
 "a_b_inbox": "📥 Support inbox ({n})", "a_b_api": "🔌 اتصال API / API connection",
 "a_stats": "📊 <b>Stats</b>\n👥 Users: {users}\n🟢 Active last 7 days: {active}\n📱 Linked phones: {phones}\n🚫 Blocked the bot: {blocked}\n💬 Open tickets: {open_t} of {all_t}\n📢 Broadcasts: {bc}\n🔌 Shop connection: {api}",
 "a_api_real": "real ✅", "a_api_mock": "mock 🧪", "a_api_none": "not set ⚪️",
 "a_bc_ask": "📢 Send the broadcast message (text or photo/media). You'll get a preview and a confirmation first.\n/cancel to abort",
 "a_bc_confirm": "👆 This message will be sent to <b>{n}</b> users. Confirm?",
 "a_bc_yes": "✅ Send it", "a_bc_no": "❌ Cancel",
 "a_bc_started": "🚀 Sending started...", "a_bc_done": "📢 Broadcast finished.\n✅ Delivered: {ok}\n🚫 Failed: {fail}",
 "a_bc_none": "There are no users to send to.", "a_bc_gone": "No pending draft.",
 "a_text_menu": "{title}\n\n<b>فارسی:</b>\n{fa}\n\n<b>English:</b>\n{en}",
 "a_text_unset": "<i>(not set)</i>",
 "a_edit_fa": "✏️ ویرایش فارسی", "a_edit_en": "✏️ Edit English", "a_reset_fa": "↩️ حذف فارسی", "a_reset_en": "↩️ Reset English",
 "a_text_ask": "✏️ Send the new text ({which}).\n/cancel to abort",
 "a_saved": "✅ Saved.", "a_title_faq": "❓ <b>FAQ</b>", "a_title_about": "📞 <b>About / Contact</b>",
 "a_inbox": "📥 <b>Support inbox</b>\nOpen tickets: {n}", "a_inbox_empty": "No tickets yet 🌱",
 "a_ticket": "🎫 <b>Ticket #{id}</b> — {status}\n👤 {who}\n\n{msgs}",
 "a_t_open": "🟢 open", "a_t_closed": "⚪️ closed",
 "a_t_reply": "✍️ Reply", "a_t_close": "✅ Close", "a_t_reopen": "🔄 Reopen", "a_t_inbox": "📥 Inbox",
 "a_t_ask": "✍️ Send your reply to ticket #{id} (text or media).\n/cancel to abort",
 "a_t_new": "📩 <b>Ticket #{id}</b> — {who}",
 "a_t_sent": "✅ Reply delivered to the user.", "a_t_fail": "⚠️ Couldn't deliver to the user (they probably blocked the bot).",
 "a_t_none": "Ticket not found.", "a_t_reply_hint": "Press “Reply” or use the messenger's Reply on that message.",
 "api_home": "🔌 <b>Shop API connection</b>\n\nStatus: {state}\n🌐 Base URL: <code>{url}</code>\n🔑 Key: <code>{key}</code>\n🔐 Auth style: {auth}\n\n<i>Config source: {src}. Values saved in the panel take priority over environment variables.</i>",
 "api_on": "🟢 enabled", "api_off": "⚪️ disabled", "api_incomplete": "🟡 incomplete (URL or key missing)",
 "api_unset": "not set",
 "api_src_panel": "panel", "api_src_env": "environment", "api_src_mixed": "panel + environment",
 "api_b_url": "🌐 Base URL", "api_b_key": "🔑 API key", "api_b_auth": "🔐 Auth style", "api_b_paths": "🛣 Endpoint paths",
 "api_b_fields": "🧬 Field mapping", "api_b_test": "🧪 Test connection", "api_b_toggle_on": "⏻ Disable", "api_b_toggle_off": "⏻ Enable",
 "api_b_clear": "🗑 Delete key",
 "api_url_ask": "🌐 Send the API base URL, e.g. <code>https://example.com/api/v1</code>\n/cancel to abort",
 "api_url_bad": "Invalid URL; it must start with http:// or https://.",
 "api_url_http": "\n⚠️ This URL is not https; the key will be sent unencrypted.",
 "api_key_ask": "🔑 Send the API key/token. Your message is deleted right after saving.\n/cancel to abort",
 "api_key_saved": "✅ Key saved: <code>{key}</code>", "api_key_del_fail": "\n⚠️ I couldn't delete the message containing the key; please delete it yourself.",
 "api_key_cleared": "🗑 Key deleted.",
 "api_key_bad": "Invalid key (empty / too long / contains spaces).",
 "api_auth_menu": "🔐 <b>Auth style</b>\nCurrent: {cur}\nHeader/param name: <code>{name}</code>",
 "api_as_bearer": "Bearer (Authorization)", "api_as_header": "X-API-Key header", "api_as_query": "Query parameter",
 "api_b_authname": "✏️ Header/param name", "api_authname_ask": "Send the header or parameter name (e.g. <code>X-API-Key</code> or <code>api_key</code>). Send <code>-</code> to reset to default.",
 "api_authname_bad": "Invalid name (English letters, digits, - and _ only).",
 "api_paths_menu": "🛣 <b>Endpoint paths</b> (relative to the base URL)\nPlaceholders: <code>{{id}} {{q}} {{page}} {{per_page}} {{category}} {{order}} {{phone}} {{user}} {{status}}</code>\n\n{lines}",
 "api_path_ask": "Send the new path for <b>{name}</b>.\nCurrent: <code>{cur}</code>\nDefault: <code>{dflt}</code>\n(must not be a full URL, e.g. <code>/products/{{id}}</code>)",
 "api_path_bad": "Invalid path; it must be relative (no http://) and short.",
 "api_reset": "↩️ Default", "api_custom": "(custom)", "api_default": "(default)",
 "api_fields_menu": "🧬 <b>JSON response field mapping</b>\nPick a group. A value may hold several keys separated by commas (first one present wins; nested paths with dots: <code>billing.phone</code>).",
 "api_fg_general": "⚙️ General", "api_fg_category": "🗂 Category", "api_fg_product": "🧴 Product", "api_fg_order": "📦 Order",
 "api_fgroup": "🧬 <b>Fields — {g}</b>\n\n{lines}",
 "api_field_ask": "Send the JSON key(s) for <b>{name}</b>.\nCurrent: <code>{cur}</code>\nDefault: <code>{dflt}</code>",
 "api_field_bad": "Invalid value (letters/digits/dot/comma/dash/underscore, max 100 chars).",
 "api_test_missing": "⚠️ First set the base URL and key, and enable the connection.",
 "api_test_running": "🧪 Testing...",
 "api_test_ok": "🧪 <b>Test result</b>\n✅ HTTP status: {status}\n⏱ {ms} ms\n📄 Items in response: {count}\n{extra}",
 "api_test_ok_sample": "🧴 Sample product: {s}",
 "api_test_ok_nomap": "⚠️ No items recognised; keys seen: <code>{keys}</code>\nAdjust the field mapping.",
 "api_test_fail": "🧪 <b>Test result</b>\n❌ {err}\n⏱ {ms} ms",
}

FA.update({"cat_all": "🛍 همه‌ی محصولات", "sup_hint": "برای خروج از پشتیبانی «{menu}» را بزن.", "sup_tail": "💬 حالت پشتیبانی فعال است؛ پیام بعدی‌ات هم ارسال می‌شود.",
           "orders_more": "… و {n} سفارش دیگر", "linked_as": "📱 {phone}", "a_bc_preview": "پیش‌نمایش پیام همگانی:", "a_no_pending": "—"})
EN.update({"cat_all": "🛍 All products", "sup_hint": "Press “{menu}” to leave support.", "sup_tail": "💬 Support mode is on; your next message is forwarded too.",
           "orders_more": "… and {n} more orders", "linked_as": "📱 {phone}", "a_bc_preview": "Broadcast preview:", "a_no_pending": "—"})

FA.update({"claim_ok": "🔐 مالکیت ربات به شما داده شد ✅ (شناسه: <code>{uid}</code>). برای ورود /admin را بزن.\nپیام حاوی کد پاک شد.",
           "claim_bad": "کد نادرست است.", "claim_locked": "⏳ تلاش‌های ناموفق زیاد بود؛ بعداً دوباره امتحان کن.",
           "claim_done": "این ربات قبلاً مالک دارد."})
EN.update({"claim_ok": "🔐 You are now the bot owner ✅ (id: <code>{uid}</code>). Send /admin to open the panel.\nThe message containing the code was deleted.",
           "claim_bad": "Wrong code.", "claim_locked": "⏳ Too many failed attempts; try again later.",
           "claim_done": "This bot already has an owner."})

FA.update({"orders_unavailable": "🧾 فهرست سفارش‌ها در این پیام‌رسان فعلاً در دسترس نیست (امکان تأیید شماره وجود ندارد).\nبا «پیگیری سفارش» و شماره‌ی سفارش می‌توانی وضعیتش را ببینی 📦"})
EN.update({"orders_unavailable": "🧾 The order list isn't available on this messenger (phone ownership can't be verified).\nUse “Track order” with your order number to see its status 📦"})

FA.update({
 "a_b_users": "👥 کاربران", "a_b_orders": "🧾 سفارش‌ها", "a_b_admins": "👮 مدیران",
 "a_owner_only": "🔒 این بخش فقط برای مالک ربات است.",
 "a_role_owner": "مالک", "a_role_admin": "مدیر",
 "banned_note": "🚫 دسترسی شما به این ربات محدود شده است.",
 # users
 "a_us_title": "👥 <b>کاربران</b> ({n}) — صفحه‌ی {page} از {pages}\n<i>مرتب‌شده بر اساس آخرین فعالیت</i>",
 "a_us_found": "🔎 نتیجه‌ی جستجوی «{q}»: {n} کاربر",
 "a_us_none": "چیزی پیدا نشد 🙈",
 "a_us_search": "🔎 جستجو", "a_us_all": "📋 همه‌ی کاربران",
 "a_us_ask": "🔎 شناسه‌ی عددی، @نام‌کاربری، بخشی از نام یا شماره‌موبایل را بفرست:",
 "a_us_card": "👤 <b>{name}</b>\n🆔 شناسه: <code>{id}</code>\n🔗 نام‌کاربری: {un}\n📅 عضویت: {joined}\n🕒 آخرین فعالیت: {seen}\n🌐 زبان: {lg}\n📱 شماره: {phone}\n💬 تیکت‌ها: {nt} (باز: {no}){extra}",
 "a_us_gone": "این کاربر پیدا نشد 🙈",
 "a_us_banned": "🚫 مسدود", "a_us_blockedbot": "⛔️ ربات را بلاک کرده",
 "a_us_msg": "✉️ ارسال پیام", "a_us_ban": "🚫 مسدود کردن", "a_us_unban": "✅ رفع مسدودی", "a_us_orders": "🧾 سفارش‌ها",
 "a_us_noban": "⚠️ مدیران را نمی‌شود مسدود کرد.",
 "a_um_ask": "✉️ پیامت را برای {who} بفرست (متن یا عکس):",
 "a_um_sent": "✅ پیام ارسال شد.",
 "a_uo_title": "🧾 <b>سفارش‌های {who}</b>", "a_uo_api": "از فروشگاه:", "a_uo_log": "پیگیری‌شده در ربات:",
 "a_uo_none": "سفارشی پیدا نشد.",
 "a_uo_nophone": "ℹ️ این کاربر شماره‌ای متصل نکرده؛ فقط سفارش‌های پیگیری‌شده در ربات نمایش داده می‌شود.",
 # orders
 "a_o_title": "🧾 <b>سفارش‌های اخیر</b> — صفحه‌ی {page} از {pages}\n🔖 فیلتر: {flt}",
 "a_o_all": "همه", "a_o_empty": "سفارشی پیدا نشد 🙈",
 "a_o_setup": "🔌 اتصال فروشگاه هنوز تنظیم نشده است. از «🔌 اتصال API» آدرس و کلید را ثبت کن.\n(جستجوی شماره‌ی سفارش و سابقه‌ی پیگیری‌ها همچنان در دسترس است.)",
 "a_o_err": "⚠️ دریافت لیست سفارش‌ها از فروشگاه ناموفق بود: <code>{err}</code>\nمسیر «لیست سفارش‌ها» را در تنظیمات API بررسی کن.",
 "a_o_search": "🔎 جستجوی شماره", "a_o_filter": "🔖 فیلتر وضعیت", "a_o_log": "🕘 پیگیری‌های کاربران",
 "a_o_filter_ask": "🔖 وضعیت مورد نظر را انتخاب کن:",
 "a_o_ask": "🔎 شماره‌ی سفارش را بفرست:",
 "a_o_notfound": "سفارش «{n}» پیدا نشد 🙈",
 "a_o_cust": "👤 مشتری", "a_o_phone": "📱 موبایل",
 "a_o_log_title": "🕘 <b>آخرین سفارش‌های پیگیری‌شده توسط کاربران</b>\n{lines}",
 "a_o_log_empty": "هنوز کسی سفارشی را در ربات پیگیری نکرده است.",
 # admins
 "a_ad_title": "👮 <b>مدیران</b>\n{lines}\n\n<i>مدیر فرعی به کاربران، سفارش‌ها، صندوق پشتیبانی و متن‌ها دسترسی دارد؛ اتصال API، پیام همگانی، مدیریت مدیران و تغییر مالک فقط برای مالک است.</i>",
 "a_ad_none": "هنوز مدیر فرعی‌ای اضافه نشده.",
 "a_ad_add": "➕ افزودن مدیر", "a_ad_owner": "👑 تغییر مالک",
 "a_ad_ask": "➕ شناسه‌ی عددی یا @نام‌کاربری فرد را بفرست (باید قبلاً به ربات پیام داده باشد):",
 "a_ad_unknown": "این کاربر را نمی‌شناسم 🙈 باید یک بار به ربات پیام داده باشد. دوباره بفرست یا لغو کن.",
 "a_ad_already": "او از قبل مدیر است ✅",
 "a_ad_added": "✅ {who} به‌عنوان مدیر اضافه شد.",
 "a_ad_notify_fail": "⚠️ اطلاع‌رسانی به او ممکن نشد.",
 "a_ad_added_note": "🎉 تو به‌عنوان <b>مدیر</b> فروشگاه اضافه شدی! پنل مدیریت را از دکمه‌ی زیر باز کن 👇",
 "a_ad_removed_note": "ℹ️ دسترسی مدیریتی تو به ربات فروشگاه برداشته شد.",
 "a_ad_rm_confirm": "❌ {who} از مدیران حذف شود؟", "a_ad_rm_yes": "✅ بله، حذف کن",
 "a_ow_ask": "👑 شناسه‌ی عددی یا @نام‌کاربری مالک جدید را بفرست (باید قبلاً به ربات پیام داده باشد):",
 "a_ow_confirm": "⚠️ <b>تغییر مالک</b>\nمالکیت به {who} منتقل شود؟ تو به مدیر فرعی تبدیل می‌شوی و دیگر نمی‌توانی این کار را برگردانی.",
 "a_ow_yes": "✅ بله، منتقل کن", "a_ow_same": "او همین الان مالک است 👑",
 "a_ow_done": "✅ مالکیت به {who} منتقل شد. تو حالا مدیر فرعی هستی.",
 "a_us_mkadm": "👮 ارتقا به مدیر", "a_us_rmadm": "👮 حذف از مدیران",
 "a_ad_banned": "🚫 این کاربر مسدود است؛ ابتدا رفع مسدودی کن، بعد او را مدیر کن.",
 "a_ad_owner_fixed": "👑 مالک را نمی‌شود از مدیریت برداشت (برای انتقال از «تغییر مالک» استفاده کن).",
 "a_ow_note_new": "👑 تو حالا <b>مالک</b> ربات فروشگاه هستی! پنل مدیریت را باز کن 👇",
})
EN.update({
 "a_b_users": "👥 Users", "a_b_orders": "🧾 Orders", "a_b_admins": "👮 Admins",
 "a_owner_only": "🔒 This section is for the bot owner only.",
 "a_role_owner": "Owner", "a_role_admin": "Admin",
 "banned_note": "🚫 Your access to this bot has been restricted.",
 "a_us_title": "👥 <b>Users</b> ({n}) — page {page} of {pages}\n<i>sorted by last activity</i>",
 "a_us_found": "🔎 Search results for “{q}”: {n} user(s)",
 "a_us_none": "Nothing found 🙈",
 "a_us_search": "🔎 Search", "a_us_all": "📋 All users",
 "a_us_ask": "🔎 Send a numeric id, @username, part of a name, or a phone number:",
 "a_us_card": "👤 <b>{name}</b>\n🆔 ID: <code>{id}</code>\n🔗 Username: {un}\n📅 Joined: {joined}\n🕒 Last active: {seen}\n🌐 Language: {lg}\n📱 Phone: {phone}\n💬 Tickets: {nt} (open: {no}){extra}",
 "a_us_gone": "That user wasn't found 🙈",
 "a_us_banned": "🚫 Banned", "a_us_blockedbot": "⛔️ Blocked the bot",
 "a_us_msg": "✉️ Send message", "a_us_ban": "🚫 Ban", "a_us_unban": "✅ Unban", "a_us_orders": "🧾 Orders",
 "a_us_noban": "⚠️ Admins can't be banned.",
 "a_um_ask": "✉️ Send your message for {who} (text or photo):",
 "a_um_sent": "✅ Message sent.",
 "a_uo_title": "🧾 <b>Orders of {who}</b>", "a_uo_api": "From the shop:", "a_uo_log": "Looked up in the bot:",
 "a_uo_none": "No orders found.",
 "a_uo_nophone": "ℹ️ This user hasn't linked a phone; only orders looked up in the bot are shown.",
 "a_o_title": "🧾 <b>Recent orders</b> — page {page} of {pages}\n🔖 Filter: {flt}",
 "a_o_all": "All", "a_o_empty": "No orders found 🙈",
 "a_o_setup": "🔌 The shop connection isn't set up yet. Add the URL and key in “🔌 API connection”.\n(Search by order number and the lookup history still work.)",
 "a_o_err": "⚠️ Couldn't fetch the orders list from the shop: <code>{err}</code>\nCheck the “orders list” path in the API settings.",
 "a_o_search": "🔎 Find by number", "a_o_filter": "🔖 Status filter", "a_o_log": "🕘 User lookups",
 "a_o_filter_ask": "🔖 Pick a status:",
 "a_o_ask": "🔎 Send the order number:",
 "a_o_notfound": "Order “{n}” wasn't found 🙈",
 "a_o_cust": "👤 Customer", "a_o_phone": "📱 Phone",
 "a_o_log_title": "🕘 <b>Latest orders looked up by users</b>\n{lines}",
 "a_o_log_empty": "Nobody has looked up an order in the bot yet.",
 "a_ad_title": "👮 <b>Admins</b>\n{lines}\n\n<i>Extra admins get users, orders, the support inbox and texts; API connection, broadcast, admin management and owner change are owner-only.</i>",
 "a_ad_none": "No extra admins yet.",
 "a_ad_add": "➕ Add admin", "a_ad_owner": "👑 Change owner",
 "a_ad_ask": "➕ Send the person's numeric id or @username (they must have messaged the bot before):",
 "a_ad_unknown": "I don't know that user 🙈 They must have messaged the bot once. Send again or cancel.",
 "a_ad_already": "They're already an admin ✅",
 "a_ad_added": "✅ {who} was added as an admin.",
 "a_ad_notify_fail": "⚠️ Couldn't notify them.",
 "a_ad_added_note": "🎉 You've been added as an <b>admin</b> of the Shop bot! Open the panel below 👇",
 "a_ad_removed_note": "ℹ️ Your admin access to the Shop bot was removed.",
 "a_ad_rm_confirm": "❌ Remove {who} from admins?", "a_ad_rm_yes": "✅ Yes, remove",
 "a_ow_ask": "👑 Send the new owner's numeric id or @username (they must have messaged the bot before):",
 "a_ow_confirm": "⚠️ <b>Change owner</b>\nTransfer ownership to {who}? You'll become an extra admin and can't undo this yourself.",
 "a_ow_yes": "✅ Yes, transfer", "a_ow_same": "They're already the owner 👑",
 "a_ow_done": "✅ Ownership transferred to {who}. You're now an extra admin.",
 "a_us_mkadm": "👮 Make admin", "a_us_rmadm": "👮 Remove admin",
 "a_ad_banned": "🚫 This user is banned; unban them first, then make them an admin.",
 "a_ad_owner_fixed": "👑 The owner can't be demoted (use “Change owner” to transfer ownership).",
 "a_ow_note_new": "👑 You're now the <b>owner</b> of the Shop bot! Open the panel 👇",
})

T = {"fa": FA, "en": EN}

FIELD_LABELS = {  # human labels for the mapping screen (fa, en)
 "list_key": ("کلید آرایه‌ی نتایج (خالی = خودکار)", "results array key (empty = auto)"),
 "pages_key": ("تعداد صفحات", "total pages"),
 "cat_id": ("شناسه‌ی دسته", "category id"), "cat_name": ("نام دسته", "category name"),
 "p_id": ("شناسه‌ی محصول", "product id"), "p_name": ("نام محصول", "product name"), "p_price": ("قیمت", "price"),
 "p_currency": ("واحد پول", "currency"), "p_image": ("تصویر", "image"), "p_url": ("لینک محصول", "product URL"),
 "p_desc": ("توضیح", "description"), "p_stock": ("موجودی", "stock"),
 "o_number": ("شماره‌ی سفارش", "order number"), "o_status": ("وضعیت سفارش", "order status"),
 "o_total": ("مبلغ کل", "order total"), "o_currency": ("واحد پول سفارش", "order currency"),
 "o_date": ("تاریخ سفارش", "order date"), "o_phone": ("موبایل سفارش‌دهنده", "customer phone"),
 "o_tracking": ("کد رهگیری", "tracking code"), "o_items": ("اقلام سفارش", "order items"),
 "o_name": ("نام مشتری", "customer name"),
 "i_name": ("نام قلم", "item name"), "i_qty": ("تعداد قلم", "item quantity"),
}
PATH_LABELS = {
 "categories": ("دسته‌ها", "categories"), "products": ("لیست محصولات", "products list"),
 "product": ("جزئیات محصول", "product detail"), "search": ("جستجو", "search"),
 "order": ("پیگیری سفارش", "order lookup"), "user_orders": ("سفارش‌های کاربر", "user orders"),
 "orders_list": ("لیست سفارش‌ها (مدیر)", "orders list (admin)"),
}


def tr(lang, key, /, **kw):
    s = T.get(lang, FA).get(key) or FA[key]
    return s.format(**kw) if kw else s


def status_label(lang, key, raw=""):
    import html
    k = "st_" + (key if ("st_" + key) in FA else "unknown")
    return tr(lang, k, raw=html.escape(raw or "?"))
